### ISSUE TITLE
Actualizar checklist de una lista ante cambios en la tarjeta

### ISSUE THREAD

**Issue by martindafonte** [martindafonte/lista-oratorio#8]
Se deben utilizar web hooks para identificar los cambios.

El webhook debe asociarse con el token del usuario de alguna forma (URL de user id?).

- [x] Al renombrar una tarjeta se debe cambiar el nombre del checkitem y mantener el estado
- [x] Al mover una tarjeta: Se debe sacar de la lista actual y agregar a la nueva
- [x] Al crear una tarjeta se debe agregar al checklist
- [x] Al borrar/archivar una tarjeta: Se debe sacar de la lista actual

**Comment by martindafonte** [comment]
Se separa la funcionalidad de mantener el estado en otro issue
